author: Moanalua Athletic Club
title: Moanalua Athletic Club 
email: palmoanalua@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Serving the Moanalua community with volunteer run baseball, basketball,
  and volleyball programs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
#theme: jekyll-theme-clean-blog
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
sass:
    sass_dir: _sass