author: Moanalua Athletic Club
title: Moanalua Athletic Club 
email: palmoanalua@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Serving the Moanalua community with volunteer run baseball, basketball,
  and volleyball programs for multiple age groups.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
